# Generated by Django 5.2.6 on 2025-09-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('contact_number', models.CharField(max_length=11)),
                ('address', models.TextField(max_length=450)),
                ('birthdate', models.DateField()),
                ('username', models.CharField(max_length=100, unique=True)),
                ('pin', models.CharField(max_length=4)),
            ],
        ),
    ]
