# Generated by Django 5.2.6 on 2025-09-22 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_patient_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
    ]
