# Generated by Django 5.2.6 on 2025-09-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_first_name_patient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='contact',
            field=models.CharField(default='N/A', max_length=11),
        ),
    ]
