# Generated by Django 5.2.6 on 2025-09-22 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
