# Generated by Django 5.2.6 on 2025-09-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pin',
            field=models.IntegerField(max_length=4),
        ),
    ]
