# Generated by Django 5.2.6 on 2025-09-23 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_patient_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pin',
            field=models.CharField(max_length=4),
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('heart_rate', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('oxygen_saturation', models.FloatField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('BMI', models.FloatField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='api.patient')),
            ],
        ),
    ]
