# Generated by Django 5.2.6 on 2025-09-25 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_patient_pin_vitalsigns'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vitalsigns',
            old_name='recorded_at',
            new_name='date_time_recorded',
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='BMI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('pin', models.CharField(max_length=6, unique=True)),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('staff', 'Healthcare Staff')], max_length=20)),
                ('patient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
    ]
