# Generated by Django 5.2.6 on 2025-09-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_recorded_at_vitalsigns_date_time_recorded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HCStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('staff_pin', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
