# Generated by Django 5.2.6 on 2025-09-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_hcstaff_delete_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='fingerprint_id',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
