# Generated by Django 5.2.6 on 2025-09-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_patient_fingerprint_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
