# Generated by Django 5.2.1 on 2025-10-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_patient_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='device_id',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
