# Generated by Django 5.2.6 on 2025-10-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_patient_name_patient_age_patient_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='middle_name',
            new_name='middle_initial',
        ),
    ]
