# Generated by Django 5.2.6 on 2025-10-07 11:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_middle_name_patient_middle_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsigns',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='oxygen_saturation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(blank=True, choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('NORMAL', 'Normal')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('SEEN', 'Seen')], default='WAITING', max_length=10)),
                ('entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='api.patient')),
            ],
            options={
                'ordering': ['-entered_at'],
            },
        ),
    ]
