# Generated by Django 5.2.6 on 2025-10-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_vitalsigns_heart_rate_alter_vitalsigns_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queueentry',
            name='status',
        ),
        migrations.AddField(
            model_name='queueentry',
            name='queue_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
