# Generated by Django 5.2.6 on 2025-10-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_queueentry_status_queueentry_queue_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
