# Generated by Django 5.2.6 on 2025-10-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_gender_patient_sex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
