# Generated by Django 5.2.6 on 2025-10-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_patient_last_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='username',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
